services:
  - type: web
    name: zeepy
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: "gunicorn zeepy.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: zeepy.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value: your-secret-key
      - key: ALLOWED_HOSTS
        value: .onrender.com,zeepy.eu

# ✅ Перенеси ВНЕ блока services
staticPublishPath: staticfiles
